### ISSUE TITLE
 no such file or directory, open './city-db.json

### ISSUE THREAD

**Issue by czco** [Cleanshooter/extract-us-city#1]
simple usage returned in the following error:

`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './city-db.json'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:363:35)
    at loadDatabase (/xxxxx/node_modules/extract-us-city/dist/index.min.js:1:84)`

checked node_modules/extract-us-city/  folder, file does exist

**Comment by Cleanshooter** [comment]
Thanks for the report, the issue is resolved in version 0.0.7.
